spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.17.80:3306/dbgirl
    username: admin
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb